### PR TITLE
Build middleware infrastructure for use cases

### PR DESCRIPTION
**Pull request by mrashed-dev**
# Description
This PR lays the foundation for the Ruby SDK to build middleware to integrate into your backend application with routes to some endpoints that would help with integrating authentication and webhook event. Currently provided routes:
*  `/nylas/generate-auth-url` - Endpoint that takes an optional email address and success redirect path, returns a URL used for authentication
*  `/nylas/exchange-mailbox-token` - Endpoint that takes a token from the JSON and exchanges that code for token, then calls a user-defined callback

This PR also includes additional integration with a Rack middleware that has these routes built in, making it only a one line addition to your already existing Rails, Sinatra, etc. application.

# Usage
Here's an example application that uses the provided routes to handle a token exchange event:

```ruby
nylas = Nylas::API.new(
    app_id: CLIENT_ID,
    app_secret: CLIENT_SECRET
)

routes = Nylas::Routes.new(nylas)
server = TCPServer.new('localhost', 1337)

#Accept Incoming Connections
loop do
  client = server.accept
  client = server.accept
  first_line = client.gets
  method_token, target, version_number = first_line.split
  response_message = ""

  # Read the HTTP request. We know it's finished when we see a line with nothing but \r\n
  request_headers = {}
  while (line = client.gets) && (line != "\r\n" && line != "")
    line = line.split(' ', 2)
    request_headers[line[0].chop] = line[1].strip
  end
  data = client.read(request_headers["Content-Length"].to_i)
  if request_headers["Content-Type"] == "application/json"
    require 'json'
    data = JSON.parse(data)
  end

  case [method_token, target]
  when ["POST", Nylas::DefaultPaths::BUILD_AUTH_URL]
    response_status_code = "200 OK"
    content_type = "text/plain"
    response_message = routes.build_auth_url(
                         scopes: ['email.read_only'],
                         email_address: data["email_address"],
                         success_url: data["success_url"],
                         client_uri: "http://localhost:3000")

  when ["POST", Nylas::DefaultPaths::EXCHANGE_CODE_FOR_TOKEN]
    response_status_code = "200 OK"
    content_type = "application/json"
    token_info = routes.exchange_code_for_token(data["code"])
    response_message = {
      access_token: token_info[:access_token]
    }.to_json
  else
    response_status_code = "200 OK"
    response_message =  "✅ Received a #{method_token} request to #{target} with #{version_number}"
    content_type = "text/plain"
  end

  # Construct the HTTP Response
  http_response = "#{version_number} #{response_status_code}\r\nContent-Type: #{content_type}\r\n\r\n#{response_message}"

  client.puts http_response
  client.close
end

server.close
```

Here's an example of the above, if it were integrated using the Rack middleware in a Rails app:

```ruby
module RailsExample
  class Application < Rails::Application
    # Initialize configuration defaults for originally generated Rails version.
    config.load_defaults 7.0
    
    def exchange_mailbox_token_callback(access_token)
      [200, { 'Content-Type' => 'application/json' }, [ { access_token: access_token[:access_token], email_address: access_token[:email_address] }.to_json ]]
    end

    nylas = Nylas::API.new(
      app_id: CLIENT_ID,
      app_secret: CLIENT_SECRET
    )
    config.middleware.use Nylas::RackBinding, nylas, ['email.read_only'], method(:exchange_mailbox_token_callback), client_uri: 'http://localhost:3000'

  end
end
```

# License
I confirm that this contribution is made under the terms of the MIT license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Comment by bmulholland** [comment]
In Rails apps, the convention for setting config like `exchange_mailbox_token_callback` and the app id/secret would be in a separate initializer file, something like `Nylas::RackBinding.config {|c| c.app_id = "APP_ID"}` etc

**Comment by mrashed-dev** [comment]
Thanks for your comments @bmulholland! It's really appreciated. I will take a look at your feedback and take action on them.

**Comment by AaronDDM** [comment]
@mrashed-dev can we get this merged for @agtang96 ?

**Comment by mrashed-dev** [comment]
Closed, we're opting to go with #399 for webhook support and we will no longer go down the route of having framework-specific bindings baked into the SDK.

**Pull request closed without merging**
