### PR TITLE
Move all files to nylas/ folder.

### PR DESCRIPTION
**Pull request by marshall-lee**
Nylas files pollute global ruby *file* namespace.
For example if i have gem called 'account' or 'contact' it could be a problem.

### CODE REVIEW

**Comment by marshall-lee** [comment]
bump (branch was rebased)

**Comment by marshall-lee** [comment]
cc @pfista

**Comment by zspencer** [comment]
@marshall-lee - This is great! I'm going to branch off your branch and merge this after we release version 3.2!

**Comment by zspencer** [comment]
I've got a PR in place that takes these in and resolves the merge conflicts. Thanks a ton for the initial work on this @marshall-lee!

**Comment by khamidou** [comment]
@marshall-lee Thanks for the PR! Before we can merge it we'd need you to sign our [CLA](https://docs.google.com/forms/d/e/1FAIpQLSdCnXWsaTkw5jhJ8DMtMu5TUI9Q-El_rCuGzkdBvnNJr8oDWQ/viewform). Thanks!

**Comment by khamidou** [comment]
@marshall-lee Please, before we can merge this could you sign our [CLA](https://docs.google.com/forms/d/e/1FAIpQLSdCnXWsaTkw5jhJ8DMtMu5TUI9Q-El_rCuGzkdBvnNJr8oDWQ/viewform)? Thanks!

**Comment by marshall-lee** [comment]
@khamidou @zspencer 

Hi! I signed the CLA and resolved all the conflicts with rebase so you can merge this one and close #132.

**Comment by zspencer** [comment]
Beautiful

**Comment by zspencer** [comment]
Resolves #132

**Comment by marshall-lee** [comment]
@zspencer thank you for that you care!

**Pull request merged**
