### PR TITLE
Each and range no longer break limit filters

### LINKED ISSUE #66: Limit filter doesn't work for collections
For example, this snippet prints subjects for the whole mailbox.

``` ruby
inbox.messages.where(:in => 'Boîte de réception', :limit => 2).each do |msg|
  puts msg.subject
end
```

### PR DESCRIPTION
**Pull request by zspencer**
I want to meditate on preserving the "evaluate each page as it's loaded" behavior overnight. Will take another stab at it in the morning

Resolves #66

### CODE REVIEW

**Comment by khamidou** [comment]
Hi @zspencer! If I understand correctly, you moved the limiting/offsetting logic from `range` to `get_model_collection`?

**Comment by khamidou** [comment]
Hi @zspencer! If I understand correctly, you moved the limiting/offsetting logic from `range` to `get_model_collection`?

**Comment by zspencer** [comment]
@khamidou - Yep, basically pulled that logic up out of range and into get_model_collection, and further refined it to support the use-cases of `#each`

**Comment by khamidou** [comment]
Talked offline – thanks for fixing this!

**Pull request merged**
