### PR TITLE
Clean up correctly returning Drafts, add use case in deltas_spec

### PR DESCRIPTION
**Pull request by singjsong**
Stemming from an Intercom thread with @khamidou / @jennielees 

Problem was that drafts were being interpreted as `Inbox::Message` objects when they were actually drafts. Adding a test case for this.

### CODE REVIEW

**Comment by grinich** [comment]
Hey @singjsong -- did [this commit](https://github.com/nylas/inbox-ruby/commit/94ffb849df49208f9830e7bb839953e3c3d74163) resolve the issue for you?

**Comment by singjsong** [comment]
Yes, was just adding in a test case for this as well.

I then added https://github.com/singjsong/inbox-ruby/commit/ce9ddac6c90fc28ca3faa9c4bf58ae2ccff06445#diff-84ccdfa4e08110177e35ef9ce93da020R122 shortly after because this did not protect against the case where a `delete` event for an `Inbox::Message` was being served.

**Comment by jennielees** [comment]
We're actually making the backend changes I mentioned elsewhere, which is why this PR hasn't been merged just yet. Sorry for the delay, @singjsong :)

**Comment by singjsong** [comment]
No worries. Anything I can update here once I know what JSON to expect?

**Comment by singjsong** [comment]
Any update on this fix on the back end? Anything I can do on my end to get this in?

**Comment by emfree** [comment]
We've actually fixed this on the backend! Delta API now correctly vends changes to drafts with `"object": "draft"`.

**Comment by singjsong** [comment]
Got it, cool. So if draft objects now have the appropriate JSON structure, I could either change back the fix to something like https://github.com/nylas/nylas-ruby/commit/94ffb849df49208f9830e7bb839953e3c3d74163#diff-84ccdfa4e08110177e35ef9ce93da020L121, along with the `delta_spec` tests (doesn't hurt to have them), or close the pull request.

**Comment by khamidou** [comment]
Closing since this problem got fixed upstream.

**Pull request closed without merging**
