### PR TITLE
Skip parsing response if content is not JSON

### PR DESCRIPTION
**Pull request by nickbair-nylas**
## Issue
The changes to response parsing that were released in v4.6.3 broke file downloads and any other API calls that did not return JSON.  Previously parse errors were rescued, but that was changed in v4.6.3.

## Fixes
1. Check the content type in the response headers, if the response is `application/json` parse it, in all other cases skip parsing.

I confirm that this contribution is made under the terms of the MIT license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Review by NHoppe — CHANGES_REQUESTED** [review]
Hi @nickbair-nylas,

Please, can you fix the new checks in the unit tests?

```
Failures:

  1) Nylas::HttpClient#execute handles content types parses JSON when given content-type == application/json
     Failure/Error:
       ::RestClient::Request.execute(method: method, url: url, payload: payload,
                                     headers: headers, timeout: timeout, &block)
     
     WebMock::NetConnectNotAllowedError:
       Real HTTP connections are disabled. Unregistered request: GET https://api.nylas.com/contacts/1234 with headers {'Accept'=>'*/*', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'Authorization'=>'Basic dG9rZW46', 'Content-Types'=>'application/json', 'Host'=>'api.nylas.com', 'User-Agent'=>'Nylas Ruby SDK 4.6.2 - 2.6.6', 'X-Nylas-Api-Wrapper'=>'ruby', 'X-Nylas-Client-Id'=>'id'}
     
       You can stub this request with the following snippet:
     
       stub_request(:get, "https://api.nylas.com/contacts/1234").
         with(
           headers: {
       	  'Accept'=>'*/*',
       	  'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3',
       	  'Authorization'=>'Basic dG9rZW46',
       	  'Content-Types'=>'application/json',
       	  'Host'=>'api.nylas.com',
       	  'User-Agent'=>'Nylas Ruby SDK 4.6.2 - 2.6.6',
       	  'X-Nylas-Api-Wrapper'=>'ruby',
       	  'X-Nylas-Client-Id'=>'id'
           }).
         to_return(status: 200, body: "", headers: {})
     
       registered request stubs:
     
       stub_request(:get, "https://api.nylas.com/contacts/1234").
         with(
           headers: {
       	  'Accept'=>'*/*',
       	  'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3',
       	  'Authorization'=>'Basic dG9rZW46',
       	  'Content-Types'=>'application/json',
       	  'Host'=>'api.nylas.com',
       	  'User-Agent'=>'Nylas Ruby SDK 4.6.2 - 2.7.0',
       	  'X-Nylas-Api-Wrapper'=>'ruby',
       	  'X-Nylas-Client-Id'=>'id'
           })
     
       ============================================================
     # /Users/natanhoppe/.rvm/gems/ruby-2.6.6/gems/webmock-3.11.1/lib/webmock/http_lib_adapters/net_http.rb:114:in `request'
     # /Users/natanhoppe/.rvm/gems/ruby-2.6.6/gems/rest-client-2.1.0/lib/restclient/request.rb:473:in `net_http_do_request'
     # /Users/natanhoppe/.rvm/gems/ruby-2.6.6/gems/rest-client-2.1.0/lib/restclient/request.rb:733:in `block in transmit'
     # /Users/natanhoppe/.rvm/gems/ruby-2.6.6/gems/webmock-3.11.1/lib/webmock/http_lib_adapters/net_http.rb:123:in `start_without_connect'
     # /Users/natanhoppe/.rvm/gems/ruby-2.6.6/gems/webmock-3.11.1/lib/webmock/http_lib_adapters/net_http.rb:150:in `start'
     # /Users/natanhoppe/.rvm/gems/ruby-2.6.6/gems/rest-client-2.1.0/lib/restclient/request.rb:727:in `transmit'
     # /Users/natanhoppe/.rvm/gems/ruby-2.6.6/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'
     # /Users/natanhoppe/.rvm/gems/ruby-2.6.6/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'
     # ./lib/nylas/http_client.rb:159:in `rest_client_execute'
     # /Users/natanhoppe/.rvm/gems/ruby-2.6.6/gems/informed-1.1.1/lib/informed.rb:158:in `inform_on'
     # /Users/natanhoppe/.rvm/gems/ruby-2.6.6/gems/informed-1.1.1/lib/informed.rb:95:in `block in inform_on'
     # ./lib/nylas/http_client.rb:84:in `execute'
     # /Users/natanhoppe/.rvm/gems/ruby-2.6.6/gems/informed-1.1.1/lib/informed.rb:158:in `inform_on'
     # /Users/natanhoppe/.rvm/gems/ruby-2.6.6/gems/informed-1.1.1/lib/informed.rb:95:in `block in inform_on'
     # ./spec/nylas/http_client_spec.rb:45:in `block (3 levels) in <top (required)>'
     # /Users/natanhoppe/.rvm/gems/ruby-2.6.6/gems/webmock-3.11.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

  2) Nylas::HttpClient#execute handles content types skips parsing when content-type is not JSON
     Failure/Error:
       ::RestClient::Request.execute(method: method, url: url, payload: payload,
                                     headers: headers, timeout: timeout, &block)
     
     WebMock::NetConnectNotAllowedError:
       Real HTTP connections are disabled. Unregistered request: GET https://api.nylas.com/contacts/1234/picture with headers {'Accept'=>'*/*', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'Authorization'=>'Basic dG9rZW46', 'Content-Types'=>'application/json', 'Host'=>'api.nylas.com', 'User-Agent'=>'Nylas Ruby SDK 4.6.2 - 2.6.6', 'X-Nylas-Api-Wrapper'=>'ruby', 'X-Nylas-Client-Id'=>'id'}
     
       You can stub this request with the following snippet:
     
       stub_request(:get, "https://api.nylas.com/contacts/1234/picture").
         with(
           headers: {
       	  'Accept'=>'*/*',
       	  'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3',
       	  'Authorization'=>'Basic dG9rZW46',
       	  'Content-Types'=>'application/json',
       	  'Host'=>'api.nylas.com',
       	  'User-Agent'=>'Nylas Ruby SDK 4.6.2 - 2.6.6',
       	  'X-Nylas-Api-Wrapper'=>'ruby',
       	  'X-Nylas-Client-Id'=>'id'
           }).
         to_return(status: 200, body: "", headers: {})
     
       registered request stubs:
     
       stub_request(:get, "https://api.nylas.com/contacts/1234/picture").
         with(
           headers: {
       	  'Accept'=>'*/*',
       	  'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3',
       	  'Authorization'=>'Basic dG9rZW46',
       	  'Content-Types'=>'application/json',
       	  'Host'=>'api.nylas.com',
       	  'User-Agent'=>'Nylas Ruby SDK 4.6.2 - 2.7.0',
       	  'X-Nylas-Api-Wrapper'=>'ruby',
       	  'X-Nylas-Client-Id'=>'id'
           })
     
       ============================================================
     # /Users/natanhoppe/.rvm/gems/ruby-2.6.6/gems/webmock-3.11.1/lib/webmock/http_lib_adapters/net_http.rb:114:in `request'
     # /Users/natanhoppe/.rvm/gems/ruby-2.6.6/gems/rest-client-2.1.0/lib/restclient/request.rb:473:in `net_http_do_request'
     # /Users/natanhoppe/.rvm/gems/ruby-2.6.6/gems/rest-client-2.1.0/lib/restclient/request.rb:733:in `block in transmit'
     # /Users/natanhoppe/.rvm/gems/ruby-2.6.6/gems/webmock-3.11.1/lib/webmock/http_lib_adapters/net_http.rb:123:in `start_without_connect'
     # /Users/natanhoppe/.rvm/gems/ruby-2.6.6/gems/webmock-3.11.1/lib/webmock/http_lib_adapters/net_http.rb:150:in `start'
     # /Users/natanhoppe/.rvm/gems/ruby-2.6.6/gems/rest-client-2.1.0/lib/restclient/request.rb:727:in `transmit'
     # /Users/natanhoppe/.rvm/gems/ruby-2.6.6/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'
     # /Users/natanhoppe/.rvm/gems/ruby-2.6.6/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'
     # ./lib/nylas/http_client.rb:159:in `rest_client_execute'
     # /Users/natanhoppe/.rvm/gems/ruby-2.6.6/gems/informed-1.1.1/lib/informed.rb:158:in `inform_on'
     # /Users/natanhoppe/.rvm/gems/ruby-2.6.6/gems/informed-1.1.1/lib/informed.rb:95:in `block in inform_on'
     # ./lib/nylas/http_client.rb:84:in `execute'
     # /Users/natanhoppe/.rvm/gems/ruby-2.6.6/gems/informed-1.1.1/lib/informed.rb:158:in `inform_on'
     # /Users/natanhoppe/.rvm/gems/ruby-2.6.6/gems/informed-1.1.1/lib/informed.rb:95:in `block in inform_on'
     # ./spec/nylas/http_client_spec.rb:56:in `block (3 levels) in <top (required)>'
     # /Users/natanhoppe/.rvm/gems/ruby-2.6.6/gems/webmock-3.11.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

Finished in 0.06603 seconds (files took 1.39 seconds to load)
117 examples, 2 failures, 11 pending

Failed examples:

rspec ./spec/nylas/http_client_spec.rb:38 # Nylas::HttpClient#execute handles content types parses JSON when given content-type == application/json
rspec ./spec/nylas/http_client_spec.rb:49 # Nylas::HttpClient#execute handles content types skips parsing when content-type is not JSON
```

**Review by NHoppe — APPROVED** [review]
LGTM

**Review by NHoppe — APPROVED** [review]
LGTM.
TravisCI is only failing due to Rubocop errors now. 👍

**Comment by nickbair-nylas** [comment]
Moving PR to draft, tests failing after merging main to resolve merge conflicts.

**Pull request merged**
