### PR TITLE
Add support for thread and message search

### PR DESCRIPTION
**Pull request by zspencer**
Resolves https://github.com/nylas/nylas-ruby/issues/126

### CODE REVIEW

**Comment by zspencer** [comment]
@khamidou - Here ya go! I spent a bit of time spinning thinking I needed to do deeper surgery, but I'm pretty happy with how this wound up.

**Comment by khamidou** [comment]
LGTM, but what about the merge conflict here?

**Comment by zspencer** [comment]
Ah damn I thought I got these yesterday. I'll fix merge conflcts and then merge it.

**Comment by khamidou** [comment]
Also, we should document this in the README!

**Comment by zspencer** [comment]
Added documentation to the README, fixed merge conflicts. Going to merge when CI passes.

**Pull request merged**
